chat/urls.py
from django.conf.urls import url
from .views import UserConversationList, UserConversationMessageList, create_chat_with_buyer, create_chat_with_seller

urlpatterns = [
    url(r'^seller/(?P<spay_id>[\-\w]+)/$', create_chat_with_seller, name='contact_seller'),
    url(r'^buyer/(?P<transaction_id>[^/]+)/$', create_chat_with_buyer, name='contact_buyer'),
    url(r'^list/$', UserConversationList.as_view(), name='list'),
    url(r'^message_list/(?P<pk>[\-\w]+)/$', UserConversationMessageList.as_view(), name='message_list'),
]

spay/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = i18n_patterns(
    url(r'', include('core.urls')),
    url(r'^admin/', admin.site.urls),

    # url(r'^api/v1/', include('spay.api_urls_v1', namespace='api-v1')),
    # url(r'^docs/', include('rest_framework_docs.urls')),

    url(r'^product/', include('product.urls', namespace="product")),
    url(r'^trade/', include('trade.urls', namespace="trade")),
    url(r'^card/', include('cards.urls', namespace="card")),
    url(r'^shipping/', include('shipping.urls', namespace="shipping")),

    url(r'^user/', include('suser.urls', namespace="user")),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^message/', include('chat.urls', namespace='chat')),

)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += i18n_patterns(
        url(r'^rosetta/', include('rosetta.urls')),
    )

trade/urls.py
from django.conf.urls import url
from .views import (
    UpdateTradeSellerView, NotRelevantTradeChange, DoneTradeChange,
    UpdateTradeBuyerView, UsersTradeList, PayTradeChange, CancelPayment,
    VarianceTradeChange, ReverseTradeChange, SendTradeChange, RejectGetTradeChange
)

urlpatterns = [
    # url(r'^new/(?P<spay_id>[\-\w]+)/$', create_trade, name='create'),

    url(r'^list/$', UsersTradeList.as_view(), name='list'),

    url(r'^update_seller/(?P<spay_id>[^/]+)/$', UpdateTradeSellerView.as_view(), name='update_as_seller'),
    url(r'^update_buyer/(?P<transaction_id>[^/]+)/$', UpdateTradeBuyerView.as_view(), name='update_as_buyer'),

    url(r'^not_relevant_buyer/(?P<transaction_id>[^/]+)/$', NotRelevantTradeChange.as_view(), name='not_relevant'),
    url(r'^receive_buyer/(?P<transaction_id>[^/]+)/$', DoneTradeChange.as_view(), name='done'),
    url(r'^pay_buyer/(?P<transaction_id>[^/]+)/$', PayTradeChange.as_view(), name='pay'),
    url(r'^cancel_payment_buyer/(?P<transaction_id>[^/]+)/$', CancelPayment.as_view(), name='cancel_payment'),
    url(r'^variance_buyer/(?P<transaction_id>[^/]+)/$', VarianceTradeChange.as_view(), name='variance'),
    url(r'^reverse_buyer/(?P<transaction_id>[^/]+)/$', ReverseTradeChange.as_view(), name='reverse'),

    url(r'^send_seller/(?P<transaction_id>[^/]+)/$', SendTradeChange.as_view(), name='send'),
    url(r'^reject_get_seller/(?P<transaction_id>[^/]+)/$', RejectGetTradeChange.as_view(), name='reject_get'),

]

templates/status/booked.html
{% load i18n %}
<div class="user-data">
    <div class="row">
        <div class="col-xs-6 no-padding-right">
            {% block left_button %}
                <a href="{% url "trade:not_relevant" trade.transaction_id %}" class="btn btn-primary inverse"
                   name="reject"
                   id="id_reject_booking">{% trans "Відмінити бронювання" %}</a>
            {% endblock %}
        </div>
        <div class="col-xs-6">
            {% block right_button %}
                <a href="{% url "trade:pay" trade.transaction_id %}" class="btn btn-primary"
                   name="receive"
                   id="id_receive">{% trans "Оплатити" %}</a>
            {% endblock %}
        </div>
    </div>
</div>

templates/status/cancel.html
{% extends "status/done.html" %}
{% load i18n %}
{% block text %}{% trans "Продавець видалив угоду" %}{% endblock %}

templates/status/cancel_payment.html
{% extends "status/done.html" %}
{% load i18n %}
{% block text %}{% trans "Ви скасувалу оплату" %}{% endblock %}

templates/status/done.html
{% load i18n %}
<div class="user-data">
    <div class="row">
        <div class="col-xs-12">
            <a href="#" class="btn btn-primary" name="good" id="id_good"
               disabled="disabled">{% block text %}{% trans "Угода виконана" %}{% endblock %}</a>
        </div>
    </div>
</div>

templates/status/not_relevant.html
{% extends "status/done.html" %}
{% load i18n %}
{% block text %}{% trans "Ви відмовились від даного товару" %}{% endblock %}

templates/status/payed.html
{% extends "status/booked.html" %}
{% load i18n %}
{% block left_button %}
    <a href="{% url "trade:cancel_payment" trade.transaction_id %}" class="btn btn-primary inverse"
       name="reject" id="id_reject_booking">{% trans "Відмінити оплату" %}</a>
{% endblock %}
{% block right_button %}
{% endblock %}

templates/status/reject_get.html
{% extends "status/done.html" %}
{% load i18n %}
{% block text %}{% trans "Продавець отримав товар назад" %}{% endblock %}

templates/status/reverse.html
{% extends "status/done.html" %}
{% load i18n %}
{% block text %}{% trans "Ви відправили товар" %}{% endblock %}

templates/status/sent.html
{% extends "status/booked.html" %}
{% load i18n %}
{% block left_button %}
    <a href="{% url "trade:done" trade.transaction_id %}" class="btn btn-primary"
       name="reject" id="id_reject_booking">{% trans "Угода успішна" %}</a>
{% endblock %}
{% block right_button %}
    <a href="{% url "trade:variance" trade.transaction_id %}" class="btn btn-primary inverse"
       name="reject" id="id_reject_booking">{% trans "Невідповідність" %}</a>
{% endblock %}

templates/status/variance.html
{% extends "status/booked.html" %}
{% load i18n %}
{% block left_button %}
    <a href="{% url "shipping:reverse" trade.transaction_id %}" class="btn btn-primary inverse"
       name="reverse" id="id_reverse_booking">{% trans "Відправити товар" %}</a>
{% endblock %}
{% block right_button %}
{% endblock %}