cards/urls.py
from django.conf.urls import url
from .views import checkout_for_payment, get_all_user_cards, AddCardView, AddAccountView, AddLegalAccountView, \
    EditCardInfoView, EditBankAccountInfoView, EditLegalBankAccountInfoView

urlpatterns = [
    # url(r'^add/(?P<product_slug>[-\w]+)/$', AddCard.as_view(), name='add_old'),
    url(r'^add/(?P<product_slug>[-\w]+)/$', checkout_for_payment, name='add'),
    # url(r'^add_bank/(?P<product_slug>[-\w]+)/$', company_payment, name='add_bank_account'),
    url(r'^list/$', get_all_user_cards, name='list'),
    url(r'^new_card/$', AddCardView.as_view(), name='card_add_manually'),
    url(r'^new_account/$', AddAccountView.as_view(), name='account_add_manually'),
    url(r'^new_legal_account/$', AddLegalAccountView.as_view(), name='legal_account_add_manually'),
    # url(r'^get_payment_form/(?P<form_type>[-\w]+)/$', get_payment_form, name='get_payment_form'),
    url(r'^edit_card/(?P<pk>[-\w]+)/$', EditCardInfoView.as_view(), name='edit_card_info'),
    url(r'^edit_bank_account/(?P<pk>[-\w]+)/$', EditBankAccountInfoView.as_view(), name='edit_bank_account_info'),
    url(r'^edit_legal_bank_account/(?P<pk>[-\w]+)/$', EditLegalBankAccountInfoView.as_view(), name='edit_legal_bank_account_info'),
]

chat/urls.py
from django.conf.urls import url
from .views import UserConversationList, UserConversationMessageList, create_chat_with_buyer, create_chat_with_seller

urlpatterns = [
    url(r'^seller/(?P<spay_id>[\-\w]+)/$', create_chat_with_seller, name='contact_seller'),
    url(r'^buyer/(?P<transaction_id>[^/]+)/$', create_chat_with_buyer, name='contact_buyer'),
    url(r'^list/$', UserConversationList.as_view(), name='list'),
    url(r'^message_list/(?P<pk>[\-\w]+)/$', UserConversationMessageList.as_view(), name='message_list'),
]

spay/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = i18n_patterns(
    url(r'', include('core.urls')),
    url(r'^admin/', admin.site.urls),

    # url(r'^api/v1/', include('spay.api_urls_v1', namespace='api-v1')),
    # url(r'^docs/', include('rest_framework_docs.urls')),

    url(r'^product/', include('product.urls', namespace="product")),
    url(r'^trade/', include('trade.urls', namespace="trade")),
    url(r'^card/', include('cards.urls', namespace="card")),
    url(r'^shipping/', include('shipping.urls', namespace="shipping")),

    url(r'^user/', include('suser.urls', namespace="user")),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^message/', include('chat.urls', namespace='chat')),

)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += i18n_patterns(
        url(r'^rosetta/', include('rosetta.urls')),
    )

cards/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.conf import settings
from product.models import Product
from .managers import WalletQuerySet


class Card(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    card_number = models.CharField(max_length=16)

    objects = models.Manager()
    wallet = WalletQuerySet.as_manager()

    @property
    def number_to_show(self):
        return self.card_number[:4] + ' **** **** ' + self.card_number[-4:]

    @property
    def cut_numbers_for_select(self):
        last_4_numbers = 'Card ' + self.number_to_show
        key = 'card-' + str(self.pk)
        data_for_select = (key, last_4_numbers)
        return data_for_select

    # def save(self, *args, **kwargs):
    #     try:
    #         card = Card.objects.get(card_number=self.card_number, user=self.user)
    #     except Card.DoesNotExist:
    #         super(Card, self).save(*args, **kwargs)
    #     else:
    #         return

    def __unicode__(self):
        return "%s" % self.card_number


class ProductCard(models.Model):
    card = models.ForeignKey(Card)
    product = models.OneToOneField(Product, related_name="product_card")

    @classmethod
    def add_card(cls, card, product):
        return cls.objects.update_or_create(product=product, defaults={"card": card})

    def __unicode__(self):
        return "%s-%s" % (self.card, self.product)


class BankAccount(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    number = models.BigIntegerField(_("Розрахунковий рахунок"))
    code = models.BigIntegerField(_("Код ЄДРПОУ (ЗКПО)"))
    mfo = models.IntegerField(_("Код банку (МФО)"))
    name = models.CharField(_("Ім'я власника рахунку"), max_length=128)
    actual_address = models.CharField(_("Фактична адреса"), max_length=512)
    legal_address = models.CharField(_("Юридична адреса"), max_length=256)

    objects = models.Manager()
    wallet = WalletQuerySet.as_manager()

    @property
    def number_to_show(self):
        return str(self.number)[:4] + ' **** **** ' + str(self.number)[-4:]

    @property
    def cut_numbers_for_select(self):
        last_4_numbers = 'Account ' + self.number_to_show
        key = 'invoice-' + str(self.pk)
        data_for_select = (key, last_4_numbers)
        return data_for_select


class ProductBankAccount(models.Model):
    bank_account = models.ForeignKey(BankAccount)
    product = models.OneToOneField(Product, related_name="product_bank_account")

    @classmethod
    def add_card(cls, card, product):
        return cls.objects.update_or_create(product=product, defaults={"bank_account": card})


class BankAccountLegal(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    number = models.BigIntegerField(_("Розрахунковий рахунок"))
    code = models.BigIntegerField(_("Код ЄДРПОУ (ЗКПО)"))
    mfo = models.IntegerField(_("Код банку (МФО)"))
    name = models.CharField(_("Найменування організації"), max_length=128)
    actual_address = models.CharField(_("Фактична адреса"), max_length=512)
    legal_address = models.CharField(_("Юридична адреса"), max_length=256)

    objects = models.Manager()
    wallet = WalletQuerySet.as_manager()

    @property
    def number_to_show(self):
        return str(self.number)[:4] + ' **** **** ' + str(self.number)[-4:]

    @property
    def cut_numbers_for_select(self):
        last_4_numbers = 'Account ' + self.number_to_show
        key = 'invoice-' + str(self.pk)
        data_for_select = (key, last_4_numbers)
        return data_for_select


class ProductBankAccountLegal(models.Model):
    bank_account = models.ForeignKey(BankAccountLegal)
    product = models.OneToOneField(Product, related_name="product_bank_account_legal")

    @classmethod
    def add_card(cls, card, product):
        return cls.objects.update_or_create(product=product, defaults={"bank_account": card})

cards/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django import forms
from .models import Card, BankAccount, ProductCard, ProductBankAccount, BankAccountLegal, ProductBankAccountLegal
from .fields import CreditCardField
from .utils import build_data_for_select, get_all_user_accounts_dict

PAYMENT_METHODS = (
    ('card', _('Отримати гроші на нову картку')),
    ('invoice', _('Отримати гроші на новий рахунок'))
)


class BaseCardForm(forms.ModelForm):
    card_number = CreditCardField(label="XXXX")

    def __init__(self, *args, **kwargs):
        super(BaseCardForm, self).__init__(*args, **kwargs)
        for field_name in self.fields:
            field = self.fields.get(field_name)
            field.widget.attrs.update(
                {'placeholder': field.label}
            )
            field.label = ''

    def clean_card_number(self):
        card_number = self.cleaned_data['card_number']
        if not (card_number.isdigit() and len(card_number) == 16):
            raise forms.ValidationError(_("Введіть правильний номер картки"))
        return card_number

    class Meta:
        model = Card
        fields = ('first_name', 'last_name', 'card_number')


class AddCardForm(BaseCardForm):
    model_to_add = ProductCard
    payment_method = forms.ChoiceField(choices=PAYMENT_METHODS)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        super(AddCardForm, self).__init__(*args, **kwargs)
        if 'payment_method' in self.fields:
            self.fields.get('payment_method').choices = build_data_for_select(self.user) + PAYMENT_METHODS

    def save(self, commit=True, product=None):
        instance = super(AddCardForm, self).save(commit=False)
        instance.user = self.user
        if commit:
            instance.save()
        self.model_to_add.add_card(instance, product)
        return instance


class AddBankAccountForm(AddCardForm):
    field_order = ('payment_method', )
    model_to_add = ProductBankAccount
    payment_method = forms.ChoiceField(choices=PAYMENT_METHODS)
    card_number = None

    class Meta:
        model = BankAccount
        fields = ('name', 'number', 'code', 'mfo', 'legal_address', 'actual_address')


class AddLegalBankAccountForm(AddBankAccountForm):
    model_to_add = ProductBankAccountLegal

    class Meta:
        model = BankAccountLegal
        fields = ('name', 'number', 'code', 'mfo', 'legal_address', 'actual_address')


class AddCompanyBankAccountForm(AddBankAccountForm):
    field_order = ()
    payment_method = None


class AddBankAccountManuallyForm(BaseCardForm):
    card_number = None

    class Meta:
        model = BankAccount
        fields = ('name', 'number', 'code', 'mfo', 'legal_address', 'actual_address')


class AddLegalBankAccountManuallyForm(BaseCardForm):
    card_number = None

    class Meta:
        model = BankAccountLegal
        fields = ('name', 'number', 'code', 'mfo', 'legal_address', 'actual_address')

cards/views.py
from django.shortcuts import redirect, get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from product.models import Product
from .forms import AddCardForm, AddBankAccountForm, AddCompanyBankAccountForm, BaseCardForm, \
    AddBankAccountManuallyForm, AddLegalBankAccountManuallyForm, AddLegalBankAccountForm
from .models import Card, BankAccount, BankAccountLegal, ProductCard, ProductBankAccount, ProductBankAccountLegal
from django.views.generic import CreateView, UpdateView
from django.core.urlresolvers import reverse_lazy
from .utils import get_all_user_accounts


def get_initial(model, request):
    initial = model.objects.filter(user=request.user).last()
    return initial if initial else None


@login_required
def checkout_for_payment(request, product_slug):
    product = get_object_or_404(Product, slug=product_slug, user=request.user)
    if request.user.type == "company":
        form_bank = AddLegalBankAccountForm(request.POST or None, user=request.user)
    else:
        form_bank = AddBankAccountForm(request.POST or None, user=request.user)
    form_card = AddCardForm(request.POST or None, user=request.user)
    if request.method == "POST":
        if request.POST.get("payment_method") == "card" and form_card.is_valid():
            form_card.save(product=product)
            return redirect('trade:list')
        elif request.POST.get("payment_method") == "invoice" and form_bank.is_valid():
            form_bank.save(product=product)
            return redirect('trade:list')
        elif request.POST.get("payment_method") not in ("card", "invoice"):
            object_pk = request.POST.get("payment_method").split('-')[1]
            if 'card' in request.POST.get("payment_method"):
                card = get_object_or_404(Card, pk=object_pk, user=request.user)
                ProductCard.add_card(card, product)
            else:
                if request.user.type == 'private':
                    account = get_object_or_404(BankAccount, pk=object_pk, user=request.user)
                    ProductBankAccount.add_card(account, product)
                else:
                    account = get_object_or_404(BankAccountLegal, pk=object_pk, user=request.user)
                    ProductBankAccountLegal.add_card(account, product)
            return redirect('trade:list')
    return render(request, 'cards/card_add.html', {"product": product,
                                                   "form_card": form_card,
                                                   "form_bank": form_bank})


@login_required
def get_all_user_cards(request):
    cards, bank_accounts = get_all_user_accounts(request.user)
    return render(request, 'cards/card_list.html', {'cards': cards, 'bank_accounts': bank_accounts})


class BaseCardView(LoginRequiredMixin, CreateView):
    success_url = reverse_lazy('card:list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(BaseCardView, self).form_valid(form)


class AddCardView(BaseCardView):
    form_class = BaseCardForm
    template_name = 'cards/card_add_manually.html'


class AddAccountView(BaseCardView):
    template_name = 'cards/account_add_manually.html'
    form_class = AddBankAccountManuallyForm


class AddLegalAccountView(AddAccountView):
    form_class = AddLegalBankAccountManuallyForm


class EditCardInfoView(LoginRequiredMixin, UpdateView):
    model = Card
    form_class = BaseCardForm
    template_name = 'cards/card_add_manually.html'
    success_url = reverse_lazy('card:list')

    # fields = ('first_name', 'last_name', 'card_number')

    def get_queryset(self):
        queryset = super(EditCardInfoView, self).get_queryset()
        return queryset.filter(user=self.request.user)


class EditBankAccountInfoView(EditCardInfoView):
    model = BankAccount
    form_class = AddBankAccountManuallyForm
    template_name = 'cards/account_add_manually.html'


class EditLegalBankAccountInfoView(EditBankAccountInfoView):
    model = BankAccountLegal
    form_class = AddLegalBankAccountManuallyForm

templates/cards/account_add_manually.html
{% extends "index.html" %}
{% load crispy_forms_tags thumbnail i18n %}
{% block content %}
    <section class="deal deal-new pt-60">
        <div class="deal-body card-body">
            <form id="card" action="." method="post" class="card">
                <div class="row form-header">
                    <div class="col-xs-12 col-sm-12">
                        <a href="{% url 'card:list' %}"><span
                                class="glyphicon glyphicon-menu-left"></span>{% trans "Назад" %}</a>
                    </div>
                </div>
                {% csrf_token %}
                {{ form | crispy }}
                <div class="user-data">
                    <div class="row">
                        <div class="col-xs-6">
                            <input type="submit" value="
                                {% if form.instance.pk %}{% trans "Змінити" %}{% else %}{% trans "Додати" %}{% endif %}"
                                   class="btn btn-primary pull-left">
                        </div>
                    </div>
                    {#                    <div class="col-xs-6">#}
                    {#                        <a class="btn btn-primary" href="{% url 'card:list' %}">Назад</a>#}
                    {#                    </div>#}
                </div>
            </form>

        </div>
    </section>
{% endblock %}

templates/cards/bank_account_form.html
{% load crispy_forms_tags %}
{{ form_bank | crispy }}

templates/cards/bank_add.html
{% extends "index.html" %}
{% load crispy_forms_tags thumbnail %}
{% block content %}
    <section class="deal deal-new pt-60">
        <div class="deal-body card-body">
            <h3 class="deal-info">Спосіб оплати (2/2)</h3>
            <form id="card" action="." method="post" class="card">
                {% csrf_token %}
                {% include "cards/bank_account_form.html" %}
                <div class="user-data">
                    <div class="col-xs-offset-3 col-xs-6">
                        <input type="submit" value="Додати" class="btn btn-primary">
                    </div>
                </div>
            </form>

        </div>
    </section>
{% endblock %}

templates/cards/card_add.html
{% extends "index.html" %}
{% load crispy_forms_tags thumbnail crispy_forms_field %}
{% block content %}
    <section class="deal deal-new pt-60">
        <div class="deal-body card-body">
            <h3 class="deal-info">Спосіб оплати (2/2)</h3>

            <form id="card" action="." method="post" class="card" novalidate>
                {% csrf_token %}

                {% include "cards/card_form.html" %}

                <div class="user-data">
                    <div class="col-xs-offset-3 col-xs-6">
                        <input type="submit" value="Додати" class="btn btn-primary">
                    </div>
                </div>
            </form>
            <form id="invoice" action="." method="post" class="card hidden" novalidate>
                {% csrf_token %}
                {% include "cards/bank_account_form.html" %}
                <div class="user-data">
                    <div class="col-xs-offset-3 col-xs-6">
                        <input type="submit" value="Додати" class="btn btn-primary">
                    </div>
                </div>
            </form>
        </div>
    </section>
{% endblock %}

{% block js %}
    <script>
        function hiddenForm(elem) {
            console.log(elem.val());
            if (elem.val() == 'card') {
                $('.js-hidden-fields').removeClass('hidden');
                $('#invoice').addClass('hidden');
                {#                $('#invoice #div_id_payment_method select').val('invoice');#}
                $('#card').removeClass('hidden');
            } else if (elem.val() == 'invoice') {
                $('.js-hidden-fields').removeClass('hidden');
                {#                $('#card #div_id_payment_method select').val('card');#}
                $('#card').addClass('hidden');
                $('#invoice').removeClass('hidden');
            } else {
                $('#card').removeClass('hidden');
                $('.js-hidden-fields').addClass('hidden');
                $('#invoice').addClass('hidden');
            }
        }
        $(document).ready(function () {
            {#            if (window.location.hash) {#}
            {#                $("form").addClass("hidden");#}
            {#                $(window.location.hash).removeClass("hidden")#}
            {#            }#}
            hiddenForm($('#div_id_payment_method select'));
            $('#div_id_card_number input').keyup(function () {
                if ($(this).val().length == $(this).attr("maxlength")) {
                    $(this).next().focus();
                }
            });

            $('#div_id_payment_method select').change(function (e) {
                        e.preventDefault();
                        hiddenForm($(this));
                        {#                        $("form").toggleClass("hidden");#}
                        {#                        window.location.hash = $(this).val();#}
                        {#                        $(this).val($("option:not(:selected)", $(this)).val())#}
                    }
            );
            $('#card #div_id_payment_method select').change(function (e) {
                        e.preventDefault();
                        $('#invoice #div_id_payment_method select').val($(this).val());
                    }
            );
            $('#invoice #div_id_payment_method select').change(function (e) {
                        e.preventDefault();
                        $('#card #div_id_payment_method select').val($(this).val());
                    }
            )
        });


    </script>
{% endblock %}

templates/cards/card_add_manually.html
{% extends "index.html" %}
{% load crispy_forms_tags thumbnail crispy_forms_field i18n %}
{% block content %}
    <section class="deal deal-new pt-60">
        <div class="deal-body card-body">
            <form id="card" action="." method="post" class="card">
                <div class="row form-header">
                    <div class="col-xs-12 col-sm-12">
                        <a href="{% url 'card:list' %}"><span
                                class="glyphicon glyphicon-menu-left"></span>{% trans "Назад" %}</a>
                    </div>
                </div>
                {% csrf_token %}
                {% block finance_form %}
                    <div class="col-xs-6 no-padding">
                        {{ form.first_name| as_crispy_field }}
                    </div>
                    <div class="col-xs-6 no-padding">
                        {{ form.last_name| as_crispy_field }}
                    </div>
                    <div class="col-xs-12 no-padding">
                        {{ form.card_number| as_crispy_field }}
                    </div>
                    <div class="user-data">
                        <div class="row">
                            <div class="col-xs-6">
                                <input type="submit" value="

                                        {% if form.instance.pk %}{% trans "Змінити" %}{% else %}{% trans "Додати" %}{% endif %}"
                                       class="btn btn-primary pull-left">
                            </div>
                        </div>
                        {#                        <div class="col-xs-6">#}
                        {#                            <a class="btn btn-primary" href="{% url 'card:list' %}">Назад</a>#}
                        {#                        </div>#}
                    </div>
                {% endblock %}
            </form>
        </div>
    </section>
{% endblock %}
{% block js %}
    <script>
        $(document).ready(function () {
            if (window.location.hash) {
                $("form").addClass("hidden");
                $(window.location.hash).removeClass("hidden")
            }
            $('#div_id_card_number input').keyup(function () {
                if ($(this).val().length == $(this).attr("maxlength")) {
                    $(this).next().focus();
                }
            });

            $('#div_id_payment_method select').change(function (e) {
                        e.preventDefault();
                        $("form").toggleClass("hidden");
                        window.location.hash = $(this).val();
                        $(this).val($("option:not(:selected)", $(this)).val())
                    }
            )
        });
    </script>
{% endblock %}

templates/cards/card_form.html
{% load crispy_forms_tags %}
<div class="col-xs-12 no-padding">
    {{ form_card.payment_method |as_crispy_field }}
</div>
<div class="js-hidden-fields">
    <div class="col-xs-6 no-padding">
        {{ form_card.first_name| as_crispy_field }}
    </div>
    <div class="col-xs-6 no-padding">
        {{ form_card.last_name| as_crispy_field }}
    </div>
    <div class="col-xs-12 no-padding">
        {{ form_card.card_number| as_crispy_field }}
    </div>
</div>

templates/cards/card_list.html
{% extends "index.html" %}
{% load staticfiles i18n %}
{% block content %}
    <section class="user-transaction">
        <div class="container card-container">
            <div class="row">
                <div class="col-md-2 col-xs-6">
                    <a class="btn btn-secondary  pull-left"
                       href="{% url 'card:card_add_manually' %}">{% trans 'Додати картку' %}</a>
                </div>
                <div class="col-md-2 col-xs-6">
                    <a class="btn btn-secondary pull-left"
                       href="{% if request.user.type == 'private' %}{% url 'card:account_add_manually' %}
                {% else %}{% url 'card:legal_account_add_manually' %}{% endif %}">{% trans 'Додати рахунок' %}</a>
                </div>
            </div>
            <div class="row cards-row">
                {% for card in cards %}

                    <div class="col-xs-12 col-md-3 card-holder">
                        <div class="col-md-12 card-view">
                            <p>{% trans "Картка" %}</p>

                            <p> {{ card.number_to_show }}</p>

                            <p class="card-edit text-right"><a
                                    href="{% url 'card:edit_card_info' card.pk %}">{% trans 'Деталі' %}</a></p>
                        </div>
                    </div>

                {% endfor %}

                {% for account in bank_accounts %}
                    <div class="col-xs-12 col-md-3 card-holder">
                        <div class="col-md-12 card-view">
                            <p>{% trans "Рахунок" %}</p>

                            <p> {{ account.number_to_show }}</p>

                            <p class="text-right card-edit">
                                <a href="{% if request.user.type == 'private' %} {% url 'card:edit_bank_account_info' account.pk %}
                        {% else %}
                    {% url 'card:edit_legal_bank_account_info' account.pk %}{% endif %}">{% trans 'Деталі' %}</a></p>

                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}