chat/urls.py
from django.conf.urls import url
from .views import UserConversationList, UserConversationMessageList, create_chat_with_buyer, create_chat_with_seller

urlpatterns = [
    url(r'^seller/(?P<spay_id>[\-\w]+)/$', create_chat_with_seller, name='contact_seller'),
    url(r'^buyer/(?P<transaction_id>[^/]+)/$', create_chat_with_buyer, name='contact_buyer'),
    url(r'^list/$', UserConversationList.as_view(), name='list'),
    url(r'^message_list/(?P<pk>[\-\w]+)/$', UserConversationMessageList.as_view(), name='message_list'),
]

product/urls.py
from django.conf.urls import url
from .views import ProductCreateView, ProductDetailViewBySpay, UsersProductsView, ProductUpdateView, remove_product

urlpatterns = [
    # url(r'^new/$', ProductCreateView.as_view(), name='create'),
    url(r'^new/(?P<type>[-\w]+)/(?P<price>[-\w]+)/$', ProductCreateView.as_view(), name='create_as'),
    url(r'^update/(?P<slug>[-\w]+)/$', ProductUpdateView.as_view(), name='update'),

    url(r'^spay/(?P<spay_id>[\-\w]+)/$', ProductDetailViewBySpay.as_view(), name='details_by_spay_id'),

    url(r'^remove/(?P<spay_id>[\-\w]+)/$', remove_product, name='remove'),

    url(r'^user/all/$', UsersProductsView.as_view(), name='user_list'),
]

spay/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = i18n_patterns(
    url(r'', include('core.urls')),
    url(r'^admin/', admin.site.urls),

    # url(r'^api/v1/', include('spay.api_urls_v1', namespace='api-v1')),
    # url(r'^docs/', include('rest_framework_docs.urls')),

    url(r'^product/', include('product.urls', namespace="product")),
    url(r'^trade/', include('trade.urls', namespace="trade")),
    url(r'^card/', include('cards.urls', namespace="card")),
    url(r'^shipping/', include('shipping.urls', namespace="shipping")),

    url(r'^user/', include('suser.urls', namespace="user")),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^message/', include('chat.urls', namespace='chat')),

)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += i18n_patterns(
        url(r'^rosetta/', include('rosetta.urls')),
    )

suser/urls.py
from django.conf.urls import url
from .views import UpdateUserView, UserDetailsView, ajax_get_user_by_email, ajax_login

urlpatterns = [
    url(r'^profile/$', UpdateUserView.as_view(), name='update'),
    url(r'^details/(?P<pk>[-\w]+)/$', UserDetailsView.as_view(), name='details'),
    url(r'^exists/$', ajax_get_user_by_email, name='exists'),
    url(r'^ajax-login/$', ajax_login, name='ajax_login')

]

product/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.crypto import get_random_string
from django.core.exceptions import PermissionDenied
from django.db import models
from django.utils.translation import ugettext_lazy as _
from slugify import slugify
from django.core.urlresolvers import reverse
from django.conf import settings
from sorl.thumbnail import ImageField
from decimal import Decimal
from .managers import ProductQuerySet


def get_spay_id():
    return get_random_string(length=6).upper()


# class Category(models.Model):
#     name = models.CharField(_(u'Назва'), max_length=20)
#     slug = models.SlugField(_(u'Slug auto'), max_length=20, unique=True)
#     order = models.PositiveIntegerField()
#
#     class Meta:
#         ordering = ('order',)
#         verbose_name = _(u'Категорія')
#         verbose_name_plural = _(u'Категорії')
#
#     def __unicode__(self):
#         return self.name


PRODUCT_TYPES = (
    ('goods', _('Товар')),
    ('service', _('Сервіс'))
)

PRODUCT_CONDITIONS = (
    ('new', _('Новий')),
    ('used', _('Б\У')),
    ('waste', _('Зламаний'))
)

NEW_PRODUCT_STATUS_NAME = _('Новий')

STATUS = (
    ('available', _("Новий")),
    ("in_deal", _("В процесі виконання")),
    ("cancel", _("Скасовано  - не актуальна угода")),
)

SWITCH_STATUS = {
    'available': ('booked', 'payed', 'cancel'),
    'booked': ('payed', 'not_relevant', 'cancel'),
    'payed': ('sent', 'cancel', 'cancel_payment'),
    'sent': ('done', 'variance', 'done'),
    'done': (),
    'variance': ('reverse',),
    'reverse': ('reject_get',),
    'cancel': (),
}

SIMILAR_STATUS_LIST = ('available', 'cancel')


class Product(models.Model):
    spay_id = models.CharField(max_length=6,
                               default=get_spay_id,
                               unique=True)
    # category = models.ForeignKey(Category, verbose_name=_(u'Категорія'), related_name='category', blank=True, null=True)
    created_date = models.DateTimeField(_('Дата створення'), auto_now_add=True)
    updated_date = models.DateTimeField(_('Дата зміни'), auto_now=True)
    name = models.CharField(_('Назва'), max_length=60)
    type = models.CharField(_('Тип'), choices=PRODUCT_TYPES, max_length=10, default='goods')
    text = models.TextField(_('Опис'))
    image = ImageField(_('Основне зображення'), upload_to='media/', blank=True)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_(u'Власник товару'))
    slug = models.SlugField(_('Slug auto'), max_length=60, unique=True)
    terms = models.TextField(_('Умови'))
    product_status = models.CharField(default='available', choices=STATUS, max_length=16)
    condition = models.CharField(_('Стан'), choices=PRODUCT_CONDITIONS, max_length=10, default='new')
    is_published = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify("%s-%s" % (self.name, self.spay_id))
        super(Product, self).save(*args, **kwargs)

    def change_product_status(self, new_status):
        if new_status in SWITCH_STATUS.get(self.status):
            self.product_status = new_status
            self.save()

    objects = models.Manager()
    users = ProductQuerySet.as_manager()

    # def get_absolute_url(self):
    #     return reverse('product:details', args=[self.slug])

    def last_transaction(self):
        last_trade = self.trade_set.last()
        return last_trade if last_trade else None

    @property
    def status(self):
        return self.product_status if self.product_status in SIMILAR_STATUS_LIST \
            else self.last_transaction().status

    @property
    def get_status_display(self):
        return self.get_product_status_display() if self.product_status in SIMILAR_STATUS_LIST \
            else self.last_transaction().get_status_display()

    def buyer_transaction(self, user):
        trade = self.trade_set.filter(buyer=user).last()
        return trade if trade else '1323123123'

    @property
    def service_price(self):
        return (self.price * Decimal(0.03)).quantize(Decimal("0.01"))

    @property
    def total_price(self):
        return self.price + self.service_price

    @property
    def list_to_cancel(self):
        return 'available', 'booked', 'payed'

    class Meta:
        verbose_name = _(u'Продук')
        verbose_name_plural = _(u'Продукти')
        ordering = ('-created_date',)

    def __unicode__(self):
        return self.name


class ProductImage(models.Model):
    images = models.ForeignKey(Product, verbose_name=_(u'Зображення'), related_name='images')
    image = ImageField(_(u'Зображення'), upload_to='media/')

    class Meta:
        verbose_name = _(u'Зображення')
        verbose_name_plural = _(u'Зображення')

    def __unicode__(self):
        return str(self.id)

product/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django import forms
from django.core.urlresolvers import reverse_lazy
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model
from trade.models import Trade
from suser.models import USER_TYPES
from .models import Product, ProductImage


class BaseProductForm(forms.ModelForm):
    email = forms.EmailField(label=_("Email продавця"), widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'ajax-url': reverse_lazy('user:exists'),
    }))
    phone = forms.CharField(label=_("Телефон продавця"), required=True, widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))
    user_type = forms.ChoiceField(label=_("Тип користувача"), initial='private', choices=USER_TYPES, required=False,
                                  widget=forms.RadioSelect(attrs={
                                      # 'class': 'form-control',
                                  }))
    password = forms.CharField(label=_("Пароль"), required=False, widget=forms.PasswordInput(attrs={
        'class': 'form-control',
    }))

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(BaseProductForm, self).__init__(*args, **kwargs)
        for field_name in self.fields:
            field = self.fields.get(field_name)
            field.widget.attrs.update(
                {'placeholder': field.label}
            )
            field.label = ' '
        if self.user.is_authenticated():
            self.fields["email"].initial = self.user.email
            self.fields['email'].widget.attrs['readonly'] = True
            self.fields["phone"].initial = self.user.phone

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists() and not self.user.is_authenticated():
            raise forms.ValidationError(_("Користувач з таким email вже зареєстрований і має залогінитись"))
        return email

    class Meta:
        model = Product
        fields = ('name', 'text', 'type', 'image', 'price', 'terms', 'condition')


class BuyProductForm(BaseProductForm):
    BUY_STATUS = "payed"

    def __init__(self, *args, **kwargs):
        super(BuyProductForm, self).__init__(*args, **kwargs)
        self.fields['product'].widget = forms.HiddenInput()

    def clean(self):
        data = super(BuyProductForm, self).clean()
        if "toBuy" in self.data:
            self.instance.status = self.BUY_STATUS
        return data

    class Meta:
        model = Trade
        fields = ('product',)


class CreateProductForm(BaseProductForm):
    email_buyer = forms.EmailField(label=_("Email покупця"), required=False, widget=forms.EmailInput(attrs={
        'class': 'form-control',
    }))
    phone_buyer = forms.CharField(label=_("Телефон покупця"), required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
    }))

    def __init__(self, *args, **kwargs):
        super(CreateProductForm, self).__init__(*args, **kwargs)
        self.fields['type'].widget = forms.HiddenInput()


class UpdateProductForm(forms.ModelForm):
    image = forms.ImageField(required=False,
                             error_messages={'invalid': _("Image files only")},
                             widget=forms.FileInput)

    def __init__(self, *args, **kwargs):
        super(UpdateProductForm, self).__init__(*args, **kwargs)
        for field_name in self.fields:
            field = self.fields.get(field_name)
            field.widget.attrs.update(
                {'placeholder': field.label}
            )
            field.label = ' '
        self.fields["type"].widget.attrs['class'] = "hidden"

    class Meta:
        model = Product
        fields = ('name', 'text', 'image', 'price', 'terms', 'type', 'condition')


class ProductImageForm(forms.ModelForm):
    image = forms.ImageField(required=False,
                             error_messages={'invalid': _("Image files only")},
                             widget=forms.FileInput)

    class Meta:
        model = ProductImage
        fields = ('image',)

product/views.py
from django.http import Http404
from django.views.generic import DetailView, ListView, CreateView, View
from django.contrib.auth import get_user_model, login, authenticate
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from extra_views import InlineFormSet, CreateWithInlinesView, UpdateWithInlinesView
from core.models import Terms
from trade.models import Trade
from .models import Product, ProductImage
from .forms import BuyProductForm, CreateProductForm, UpdateProductForm, ProductImageForm


class ImagesInline(InlineFormSet):
    model = ProductImage
    form_class = ProductImageForm
    fields = ('image',)
    extra = 4
    max_num = 4


class SpayLogicMixin(object):
    def get_form_kwargs(self):
        kwargs = super(SpayLogicMixin, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def _form_valid(self, form):
        if self.request.user.is_authenticated():
            setattr(form.instance, self.form_user_attr_name, self.request.user)
        else:
            user, password = get_user_model().objects.create_user_shortcut(
                form.cleaned_data.get('email'),
                form.cleaned_data.get('phone'),
                type=form.cleaned_data.get('user_type')
            )
            setattr(form.instance, self.form_user_attr_name, user)
            user = authenticate(email=user.email, password=password)
            if user is not None:
                login(self.request, user)

    def forms_valid(self, form, inlines):
        self._form_valid(form)
        return super(SpayLogicMixin, self).forms_valid(form, inlines)

    def form_valid(self, form):
        self._form_valid(form)
        return super(SpayLogicMixin, self).form_valid(form)


class ProductCreateView(SpayLogicMixin, CreateWithInlinesView):
    template_name = "product/create_product.html"
    model = Product
    form_class = CreateProductForm
    context_object_name = 'product'
    form_user_attr_name = 'user'
    inlines = [ImagesInline]

    def get_initial(self):
        if self.kwargs.get('price'):
            return {
                'price': self.kwargs.get('price'),
                'type': self.kwargs.get('type'),
            }
        return super(ProductCreateView, self).get_initial()

    def get_context_data(self, **kwargs):
        context = super(ProductCreateView, self).get_context_data(**kwargs)
        context['terms'] = Terms.objects.first()
        return context

    def get_success_url(self):
        return reverse('card:add', args=[self.object.slug])


class ProductDetailViewBySpay(SpayLogicMixin, CreateView):
    template_name = "product/product_buy.html"
    slug_field = "spay_id"
    form_class = BuyProductForm
    model = Trade
    product = Product.objects.none()
    success_url = 'user/profile/'
    form_user_attr_name = 'buyer'

    def get_initial(self):
        initial = super(ProductDetailViewBySpay, self).get_initial()
        try:
            initial['product'] = Product.objects.get(spay_id=self.kwargs[self.slug_field])
        except Product.DoesNotExist:
            raise Http404
        return initial

    def get_context_data(self, **kwargs):
        context = super(ProductDetailViewBySpay, self).get_context_data(**kwargs)
        context['product'] = self.get_initial().get('product')
        return context

    def get_success_url(self):
        if self.request.user.type == "private" and \
                        self.object.status == self.form_class.BUY_STATUS:
            return "https://www.liqpay.com/"
        else:
            return reverse('trade:list')


class UsersObjectMixin(object):
    def get_object(self, queryset=None):
        queryset = self.model.objects.filter(user=self.request.user)
        return super(UsersObjectMixin, self).get_object(queryset)

    def get_queryset(self):
        queryset = super(UsersObjectMixin, self).get_queryset()
        return queryset.filter(user=self.request.user)


class UsersProductsView(ListView, UsersObjectMixin):
    template_name = "product_list.html"
    model = Product


class ProductUpdateView(LoginRequiredMixin, UpdateWithInlinesView):
    template_name = "product/product_update.html"
    model = Product
    form_class = UpdateProductForm
    context_object_name = 'product'
    inlines = [ImagesInline]

    def get_success_url(self):
        return reverse('trade:update_as_seller', args=(self.object.spay_id,))

    def get_object(self, queryset=None):
        return super(ProductUpdateView, self).get_object(
            self.model.users.seller(self.request.user).filter(product_status="available"))


# class ProductPostCreateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
#     template_name = "create_product.html"
#     model = Product
#     context_object_name = 'product'
#     fields = ('name', 'text', 'image', 'price')
#
#     def form_valid(self, form):
#         form.instance.user = self.request.user
#         form.instance.is_published = True
#         return super(ProductPostCreateView, self).form_valid(form)
#
#     def test_func(self):
#         return self.get_object().is_published is False


# class ProductDetailView(DetailView):
#     template_name = "product/product_change_status_seller.html"
#     model = Product
#     context_object_name = 'product'
#     buttons_template_name = "status/seller/available.html"


def change_product_status(request, spay_id, new_status):
    product = get_object_or_404(Product, spay_id=spay_id, user=request.user)
    product.change_product_status(new_status)
    return product


@login_required
def remove_product(request, spay_id, status='cancel'):
    product = change_product_status(request, spay_id, status)
    if product.last_transaction():
        product.last_transaction().change_trade_status(status)
    return redirect("trade:list")

templates/product/create_product.html
{% extends "index.html" %}
{% load crispy_forms_tags thumbnail crispy_forms_field i18n static %}
{% block content %}
    <section class="deal deal-new" xmlns="http://www.w3.org/1999/html">
        <div class="deal-body">
            <h3 class="deal-info">{% trans "Створити нову угоду" %}</h3>

            <form  autocomplete="off" action="." method="post" enctype="multipart/form-data" class="create-product-form">
                {% include "product/form.html" %}
                <div class="col-xs-6">
                    {{ form.email|as_crispy_field }}
                </div>
                <div class="col-xs-6">
                    {{ form.email_buyer|as_crispy_field }}
                </div>
                <div class="col-xs-6">
                    {{ form.phone|as_crispy_field }}
                </div>
                <div class="col-xs-6">
                    {{ form.phone_buyer|as_crispy_field }}
                </div>
                {% if not request.user.is_active %}
                    <div class="col-xs-6">
                        {{ form.password|as_crispy_field }}
                    </div>
                    <div class="col-xs-12">
                        {{ form.user_type|as_crispy_field }}
                    </div>

                    <div class="col-xs-12" id="to_show" style="display: none">
                        <div class="form-group" id="div_id_login">
                            <div class="controls text-center">
                                <a type="submit" href="#" ajax-url="{% url 'user:ajax_login' %}"
                                   class="margin-clear btn btn-primary"
                                   id="login">{% trans "Вхід" %}</a>
                            </div>
                        </div>
                    </div>
                {% endif %}

                <div class="col-xs-12 no-float">
                    <div class="form-group">
                        <input type="checkbox" id="cbTerms"/>
                        <label for="cbTerms"></label>
                        <span class="terms" data-toggle="modal"
                              data-target="#myModal">{% trans "Я погоджуюсь з умовами використання сервісу" %}</span>
                    </div>
                </div>
                <div class="col-xs-12">
                    <div class="form-group">
                        <input type="submit" value="Продати" class="btn btn-primary js-accept" disabled>
                    </div>
                </div>
            </form>
        </div>
    </section>
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">{% trans "Умови використання сервісу" %}</h4>
                </div>
                <div class="modal-body">
                    {{ terms.legal_entity }}
                </div>

            </div>
        </div>
    </div>
{% endblock %}
{% block js-product %}
    <script src="{% static  "js/product.js" %}"></script>
{% endblock %}

templates/product/product_buy.html
{% extends "index.html" %}
{% load thumbnail crispy_forms_tags i18n static %}
{% block content %}
    <section class="deal">
        <div class="wrapper">
            <div class="deal-body deal-details">
                <h3 class="deal-info">{% block deal_title %}{% trans "Деталі угоди" %}{% endblock %}</h3>

                <div class="item-header">
                    {% block back_button %}{% endblock %}
                    <div class="item-image col-xs-4 no-float">
                        {% thumbnail product.image "180x180" crop="center" as im %}
                            <img id="id_image_main" src="{{ im.url }}" class="js-gallery first-image">
                        {% endthumbnail %}
                    </div>
                    <div class="item-info-main col-xs-10 no-float">
                        <hgroup>
                            <h2 id="item-name">{{ product.name }} </h2>

                            <h3 id="item-price">За {{ product.total_price }}
                                <span>(вартість товару - {{ product.price }}; комісія - {{ product.service_price }})</span>
                            </h3>
                        </hgroup>
                        <p id="condition-id">{% trans "Стан" %}: {{ product.get_condition_display }}</p>
                        {% block product_status %}{% endblock %}
                        <p id="item-id">SPay ID: {{ product.spay_id }}</p>

                        {% block contact_user %}
                            <p id="item-seller">{% trans "Продавець" %}: {{ product.user.name_to_display }}</p>
                            <a class="btn btn-primary contact"
                               href="{% url "chat:contact_seller" product.spay_id %}">{% trans "Написати продавцю" %}</a>
                        {% endblock %}
                    </div>
                </div>
                <div class="item-description">
                    <p>
                        {{ product.text }}
                    </p>

                    <p id="terms">
                        {% trans "Умови продажу" %}:
                        {{ product.terms }}
                    </p>
                </div>
                {% block product_bottom %}
                    <div class="user-data">
                        {% if product.status  == "available" %}
                            <form class="user-data product-buy-form" method="post" action=".">
                                {% csrf_token %}
                                {{ form.product }}
                                <div class="col-xs-12 col-sm-6">
                                    {{ form.email|as_crispy_field }}
                                </div>
                                <div class="col-xs-12 col-sm-6">
                                    {{ form.phone|as_crispy_field }}
                                </div>
                                <div class="col-xs-12 col-sm-6" style="display: none">
                                    {{ form.password|as_crispy_field }}
                                </div>
                                {% if not request.user.is_active %}
                                    <div class="col-xs-12">
                                        {{ form.user_type|as_crispy_field }}
                                    </div>
                                {% endif %}
                                <div class="col-xs-12 text-center" style="display: none">
                                    <div class="form-group" id="div_id_login">
                                        <div class="controls">
                                            <a type="submit" class="btn btn-primary half" href="#"
                                               ajax-url="{% url 'user:ajax_login' %}"
                                               id="login">{% trans "Вхід" %}</a>
                                        </div>
                                    </div>
                                </div>
                                {% if product.user != request.user %}
                                    <div class="col-xs-12 no-padding no-float">
                                        <div class="form-group">
                                            <div class="controls">
                                                <input type="checkbox" id="cbTerms"/>
                                                <label for="cbTerms"></label>
                                            <span class="terms" data-toggle="modal"
                                                  data-target="#myModal">{% trans "Я погоджуюсь з умовами використання сервісу" %}</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xs-6">
                                        <input type="submit" class="btn btn-primary inverse js-accept" name="toBook"
                                               id="id_toBook"
                                               disabled value="{% trans "Забронювати" %}">
                                    </div>
                                    <div class="col-xs-6">
                                        <input type="submit" class="btn btn-primary js-accept" name="toBuy"
                                               id="id_toBuy"
                                               disabled
                                               value="{% trans "Оплатити" %}">
                                    </div>
                                {% else %}
                                    <div class="row">
                                        <div class="col-xs-6">
                                            <a type="submit" href="{% url "product:update" product.slug %}"
                                               class="btn btn-primary">{% trans "Редагувати" %}</a>
                                        </div>
                                    </div>

                                {% endif %}
                            </form>
                        {% else %}
                            <div class="col-xs-12 no-padding">
                                <input type="submit" class="btn btn-primary grey" id="btnProceed" disabled
                                       value="{{ product.get_status_display }}">
                            </div>
                        {% endif %}
                    </div>
                {% endblock %}
            </div>
        </div>
    </section>
    {% block modal %}
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">{% trans "Умови використання сервісу" %}</h4>
                    </div>
                    <div class="modal-body">
                        {{ terms.legal_entity }}
                    </div>

                </div>
            </div>
        </div>
    {% endblock %}
{% endblock %}
{% block js-product %}
    <script src="{% static  "js/product.js" %}"></script>
{% endblock %}
{% block js %}
    <script src="{% static  "lightgallery/js/lightgallery.min.js" %}"></script>
    <script type="text/javascript">
        $(".js-gallery").click(function () {
            $(this).lightGallery({
                width: '700px',
                height: '460px',
                mode: 'lg-fade',
                addClass: 'fixed-size',
                counter: false,
                download: false,
                startClass: '',
                enableSwipe: false,
                enableDrag: false,
                speed: 500,
                dynamic: true,
                dynamicEl: [{
                    'src': {% thumbnail product.image "x400" crop="center" as im %}'{{im.url }}'{% endthumbnail %}
                },
                    {% for image in product.images.all %}
                        {% thumbnail image.image "x400" crop="center" as im %}
                            {'src': '{{ im.url }}'},
                        {% endthumbnail %}
                    {% endfor %}
                ]
            });
        })
        ;
    </script>
{% endblock %}

templates/product/product_change_status_seller.html
{% extends "product/product_buy.html" %}
{% load thumbnail crispy_forms_tags i18n %}
{% block deal_title %}{% trans "Змінити статус (продавець)" %}{% endblock %}
{% block back_button %}
    <div class="row form-header mb-10">
        <div class="col-xs-6 col-sm-6">
            <a href="{% url "trade:list" %}"><span
                    class="glyphicon glyphicon-menu-left"></span>{% trans "Назад" %}</a>
        </div>

        <div class="col-xs-6 col-sm-6">
            {% if product.status in product.list_to_cancel %}
                <a class="pull-right" href="{% url "product:remove"  product.spay_id %}"><span
                        class="glyphicon glyphicon-trash"></span> {% trans "Видалити" %}</a>
            {% endif %}
        </div>
    </div>
{% endblock %}
{% block product_status %}<p id="status_id">{% trans "Статус" %}: {{ product.get_status_display }}</p> {% endblock %}
{% block contact_user %}
    {% if product.last_transaction %}
        <p id="item-seller">{% trans "Покупець" %}: {{ product.last_transaction.buyer.name_to_display }}</p>
        <a class="btn btn-primary contact"
           href="{% url "chat:contact_buyer" product.last_transaction.transaction_id %}">{% trans "Написати покупцю" %}</a>
    {% endif %}
{% endblock %}
{% block product_bottom %}
    {% include buttons_template_name %}
{% endblock %}
{% block modal %}{% endblock %}