chat/urls.py
from django.conf.urls import url
from .views import UserConversationList, UserConversationMessageList, create_chat_with_buyer, create_chat_with_seller

urlpatterns = [
    url(r'^seller/(?P<spay_id>[\-\w]+)/$', create_chat_with_seller, name='contact_seller'),
    url(r'^buyer/(?P<transaction_id>[^/]+)/$', create_chat_with_buyer, name='contact_buyer'),
    url(r'^list/$', UserConversationList.as_view(), name='list'),
    url(r'^message_list/(?P<pk>[\-\w]+)/$', UserConversationMessageList.as_view(), name='message_list'),
]

product/urls.py
from django.conf.urls import url
from .views import ProductCreateView, ProductDetailViewBySpay, UsersProductsView, ProductUpdateView, remove_product

urlpatterns = [
    # url(r'^new/$', ProductCreateView.as_view(), name='create'),
    url(r'^new/(?P<type>[-\w]+)/(?P<price>[-\w]+)/$', ProductCreateView.as_view(), name='create_as'),
    url(r'^update/(?P<slug>[-\w]+)/$', ProductUpdateView.as_view(), name='update'),

    url(r'^spay/(?P<spay_id>[\-\w]+)/$', ProductDetailViewBySpay.as_view(), name='details_by_spay_id'),

    url(r'^remove/(?P<spay_id>[\-\w]+)/$', remove_product, name='remove'),

    url(r'^user/all/$', UsersProductsView.as_view(), name='user_list'),
]

spay/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = i18n_patterns(
    url(r'', include('core.urls')),
    url(r'^admin/', admin.site.urls),

    # url(r'^api/v1/', include('spay.api_urls_v1', namespace='api-v1')),
    # url(r'^docs/', include('rest_framework_docs.urls')),

    url(r'^product/', include('product.urls', namespace="product")),
    url(r'^trade/', include('trade.urls', namespace="trade")),
    url(r'^card/', include('cards.urls', namespace="card")),
    url(r'^shipping/', include('shipping.urls', namespace="shipping")),

    url(r'^user/', include('suser.urls', namespace="user")),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^message/', include('chat.urls', namespace='chat')),

)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += i18n_patterns(
        url(r'^rosetta/', include('rosetta.urls')),
    )

suser/urls.py
from django.conf.urls import url
from .views import UpdateUserView, UserDetailsView, ajax_get_user_by_email, ajax_login

urlpatterns = [
    url(r'^profile/$', UpdateUserView.as_view(), name='update'),
    url(r'^details/(?P<pk>[-\w]+)/$', UserDetailsView.as_view(), name='details'),
    url(r'^exists/$', ajax_get_user_by_email, name='exists'),
    url(r'^ajax-login/$', ajax_login, name='ajax_login')

]

trade/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import base64
import uuid
from model_utils.models import TimeStampedModel
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import PermissionDenied
from model_utils import Choices
from .managers import TradeQuerySet

SHIPPING = Choices("Нова Пошта",
                   "DHL")


def generate_transaction_id():
    return base64.b64encode(uuid.uuid4().bytes).replace('=', '').replace('/', '')


STATUS = (
    ("booked", _("Заброньований")),
    ("payed", _("Оплачено, Очікує виконання")),
    ("sent", _("Товар отправлен")),
    ("done", _("Сделка состоялась")),
    ("variance", _("Скасовано - несоответствие")),
    ("reverse", _("Скасовано - зворотня відправка")),
    ("reject_get", _("Скасовано - отримано")),
    ("cancel_payment", _("Скасовано оплату покупцем")),
    ("not_relevant", _("Скасовано - не актуально покупцю")),
    ("cancel", _("Скасовано  - не актуальна угода"))
)

SWITCH_STATUS = {
    'available': ('booked', 'payed', 'cancel'),
    'booked': ('payed', 'not_relevant', 'cancel'),
    'payed': ('sent', 'cancel', 'cancel_payment'),
    'sent': ('done', 'variance', 'done'),
    'done': (),
    'variance': ('reverse',),
    'reverse': ('reject_get',),
    'cancel': (),
}

AUTO_NEW_STATUS = ('cancel_payment', 'not_relevant')


class Trade(TimeStampedModel):
    buyer = models.ForeignKey(settings.AUTH_USER_MODEL,
                              to_field="spay_id",
                              verbose_name="Покупець",
                              related_name='buyer',
                              blank=True,
                              null=True)
    transaction_id = models.CharField("Transaction id",
                                      max_length=22,
                                      unique=True,
                                      default=generate_transaction_id)
    status = models.CharField("Статус", default="booked", choices=STATUS, max_length=32)
    product = models.ForeignKey('product.Product',
                                verbose_name="Товар", )

    objects = models.Manager()
    users = TradeQuerySet.as_manager()

    def save(self, *args, **kwargs):
        if not self.pk:
            self.product.product_status = 'in_deal'
            self.product.save()
        super(Trade, self).save(*args, **kwargs)

    def change_trade_status(self, status):
        if status in SWITCH_STATUS.get(self.status):
            self.status = status
            self.save()
            if self.status in AUTO_NEW_STATUS:
                self.product.product_status = "available"
                self.product.save()
        else:
            raise PermissionDenied

    @property
    def seller(self):
        return self.product.user

    def __unicode__(self):
        return u"{0}-{1}".format(self.product.name, self.transaction_id)

templates/conversation.html
{% extends "index-shop.html" %}
{% block content %}
    <div class="container">
        <table class="table table-striped">
            <tr>
                <th>from</th>
                <th>to</th>
                <th>text</th>
                <th>date</th>
            </tr>
            {% for message in object_list %}
                <tr>
                    <td>{{ message.from_user }}</td>
                    <td>{{ message.to_user }}</td>
                    <td>{{ message.text }}</td>
                    <td>{{ message.created_date }}</td>
                </tr>
            {% empty %}
                <span>No messages</span>
            {% endfor %}
        </table>
        <form action="." method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send">
        </form>
    </div>
{% endblock %}

templates/index.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
    <title>Spay - Main Page</title>

    <!-- FAVICON -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static "img/fav.png" %}"/>
    <!-- Stylesheets -->
    <link rel="stylesheet" type="text/css" href="{% static  "css/bootstrap.min.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/animate.min.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "lightgallery/css/lightgallery.min.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap-datepicker.min.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static "phone_field/css/intlTelInput.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static  "css/styles.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static  "css/custom.css" %}">
</head>

<body class="container-fluid">
<header>
    <div class="col-xs-3 col-sm-offset-1 sitelogo pull-left">
        <a href="{% url "index" %}"><img src="{% static  "img/spay_logo.png" %}"/></a>
    </div>
    <div class="col-xs-9 col-sm-5 col-sm-offset-right-1 settings pull-right">
        {% if request.user.is_authenticated %}
            <div class="btn-group notify js-notify" chat-list-url="{% url "chat:list" %}">
                <a href="{% url "chat:list" %}">
                    <span class="glyphicon glyphicon-envelope"></span>
                </a>
            <span id="messages_count" class="badge badge-notify">{% if messages_count %}
                {{ messages_count }}{% endif %}</span>
            </div>
        {% endif %}
        <div class="custom-select small language">
            {% get_current_language as current_lang %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            <div class="selected">{{ current_lang }}</div>
            <ul class="options">
                {% for language in languages %}
                    <li><a href="/{{ language.code }}{{ request.get_full_path|slice:'3:' }}"
                           data-value="{{ language.code }}">{{ language.code }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div id="id_regirtered" class="btn-group {% if not request.user.is_authenticated %}hidden{% endif %} ">
            <button type="button" class="btn btn-secondary btn-sm auth dropdown-toggle" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">{% trans "Кабінет" %}
                <span class="sr-only">{% trans "Кабінет" %}</span>
            </button>
            <ul class="dropdown-menu main">
                <li><a class="btn btn-secondary list" href="{% url "user:update" %}">{% trans "Мій профіль" %}</a></li>
                <li><a class="btn btn-secondary list" href="{% url "trade:list" %}">{% trans "Мої угоди" %}</a></li>
                <li><a class="btn btn-secondary list" href="{% url "index" %}">{% trans "Нова угода" %}</a></li>
                <li><a class="btn btn-secondary list" href="{% url "card:list" %}">{% trans "Гаманець" %}</a></li>
                <li role="separator" class="divider"></li>
                <li><a class="btn btn-secondary list last" href="{% url "account_logout" %}">{% trans "Вихід" %}</a>
                </li>
            </ul>
        </div>
        <a id="id_signin" class="btn btn-secondary btn-sm auth {% if request.user.is_authenticated %}hidden{% endif %}"
           href="{% url "account_login" %}?next={{ request.path }}">{% trans "Вхід" %}</a>

    </div>
</header>
{% block content %}
    <section class="home">
        <div class="intro">
            <h1>SPay</h1>

            <h2>{% trans "Захищені Угоди" %}<br/>{% trans "Онлайн" %}</h2>

            <form method="post" action=".">
                {% csrf_token %}
                <div>
                    <div class="custom-select" id="entity">
                        <div class="selected">{% trans "Я продаю" %}</div>
                        <ul class="options">
                            <li id="option-sell"><a href="#" data-value="sell">{% trans "Я продаю" %}</a></li>
                            <li id="option-buy"><a href="#" data-value="buy">{% trans "Я купую" %}</a></li>

                        </ul>
                        <input type="hidden" id="action_input" name="action" value="sell">
                    </div>
                    <div class="custom-select" id="ddlItem">
                        <div class="selected">{% trans "товар" %}</div>
                        <ul class="options">
                            <li id="option-goods"><a href="#" data-value="goods">{% trans "товар" %}</a></li>
                            <li id="option-service"><a href="#" data-value="service">{% trans "послугу" %}</a></li>
                        </ul>
                        <input type="hidden" id="type_input" name="type" value="goods">
                    </div>
                    <input type="number" id="tbPrice" data-title="{% trans "Потрібно ввести ціну" %}"
                           data-placement="right"
                           name="price" class="text-center form-control"
                           placeholder="{% trans "за 499 грн." %}"/>
                </div>
                <div class="spay-qustion-mark">
                    <input type="text" id="tbSpayId" name="spay_id" data-placement="right"
                           class="text-center form-control" placeholder="SPay ID: XXXXXX"
                           style="visibility: hidden;" maxlength="6" data-title="{% trans "Введіть Spay ID" %}">
                    <label data-toggle="tooltip" data-placement="right"
                           title="{% trans "Це Spay ID" %}"><span id="question_mark"
                                                                  class="glyphicon glyphicon-question-sign info-sign"></span></label>
                </div>
                <div>
                    <a class="btn btn-secondary" name="getStarted" value="" id="btnGetStarted">{% trans "Почати" %}</a>
                </div>
            </form>
        </div>
    </section>
{% endblock %}
<footer class="footer">
    <ul class="links">
        <li><a href="#">{% trans "Часті запитання" %}</a></li>
        <li><a href="#">{% trans "Сервіс" %}</a></li>
    </ul>
    <div class="copyright">
        Copyright &copy; 2016 SPay. All rights reserved
    </div>
    <ul class="col-xs-offset-right-1 social pull-right">
        <li><a class="soc-facebook" href="#"></a></li>
        <li><a class="soc-twitter" href="#"></a></li>
        <li><a class="soc-youtube soc-icon-last" href="#"></a></li>
    </ul>
</footer>

<script src="{% static  "js/jquery-1.12.3.min.js" %}"></script>
<script src="{% static  "js/mask.js" %}"></script>
<script src="{% static  "js/bootstrap.min.js" %}"></script>
<script src="{% static  "js/reconnecting-websocket.min.js" %}"></script>
<script src="{% static  "js/jquery.nicescroll.min.js" %}"></script>
<script src="{% static  "js/numeric.js" %}"></script>
<script src="{% static  "phone_field/js/intlTelInput.min.js" %}"></script>
<script src="{% static  "js/bootstrap-notify.js" %}"></script>
<script src="{% static  "js/scripts.js" %}"></script>
<script src="{% static  "js/main.js" %}"></script>
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
<script type="text/javascript" src="{% static "js/ajax-settings.js" %}"></script>
<script type="text/javascript" src="{% static "js/calls.js" %}"></script>
{% block js-product %}
{% endblock %}
<script src="{% static  "js/clipboard.min.js" %}"></script>
{% block js %}
{% endblock %}


</body>
</html>

templates/product_list.html
{% extends "index-shop.html" %}

{% block content %}
    <div class="container">

        <table class="table table-striped">
            <tr>
                <th>Назва</th>
                <th>Опис</th>
                <th>Ціна</th>
            </tr>
            {% for product in object_list %}
                <tr>
                    <td>{{ product.name }}</td>
                    <td>{{ product.text }}</td>
                    <td>{{ product.price }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

templates/trade_details.html
{% extends "index.html" %}
{% block content %}
    <div class="container">
        <p><span>Назва</span> {{ trade.product.name }}</p>

        <p><span>Опис</span> {{ trade.product.text }}</p>

        <p><span>Ціна</span> {{ trade.product.price }}</p>

        <p><span>Номер транзакции</span> {{ trade.transaction_id }}</p>

        <p><span>Статус</span> {{ trade.status }}</p>
    </div>
{% endblock %}

templates/user_details_view.html
{% extends "index-shop.html" %}
{% block content %}
    <section class="section light-gray-bg clearfix">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <!-- pills start -->
                    <!-- ================ -->
                    <!-- Nav tabs -->
                    <ul class="nav nav-pills" role="tablist">
                        <li class="active"><a href="#pill-1" role="tab" data-toggle="tab" title="Мій профіль"><i
                                class="icon-star"></i> Профіль користувача</a></li>

                    </ul>
                    <!-- Tab panes -->
                    <div class="tab-content clear-style">
                        <div class="tab-pane active" id="pill-1">
                            <div class="row masonry-grid-fitrows grid-space-10">
                                <div class="col-sm-4">
                                    <p>{{ user.name }}</p>

                                    <p>{{ user.email }}</p>

                                    <p>{{ user.phone }}</p>
                                </div>
                            </div>
                        </div>

                    </div>
                    <!-- pills end -->
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/user_profile.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <section class="deal pt-60">
        <div class="deal-body ">
            <h3 class="deal-info">Профіль <span>({{ request.user.get_type_display }})</span></h3>

            <div class="col-xs-12">
                <form action="." method="post">
                    {% csrf_token %}
                    {{ form| crispy }}
                    <div class="row">
                        <div class="col-xs-6">
                            <input type="submit" class="btn btn-primary" value="Змінити">
                        </div>
                        <div class="col-xs-6 xs-padding-left">
                            <a class="btn btn-primary inverse pull-right" href="{% url "account_change_password" %}">Змінити
                                пароль</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

templates/user_transactions.html
{% extends "index.html" %}
{% load product_tags thumbnail staticfiles i18n %}
{% block content %}
    <section class="user-transaction">

        <div class="row">
            {% if filter.qs or request.GET%}
                <div class="col-sm-10 col-sm-offset-1 pull-left">
                    <h3 class="deal-info">{% trans "Список угод" %}</h3>
                </div>
                <div class="col-sm-10 col-sm-offset-1 pt-30-custom">

                    <div class="user-content">
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active" id="active_deals">
                                <form method="get" action="" id="filter_form">
                                    <table class="table table-hover table-fixed transactions"
                                           style="border-collapse:collapse;">
                                        <thead>
                                        <tr data-toggle="collapse" data-target="#filter"
                                            class="filter-pointer">
                                            <th>SpayId</th>
                                            <th class="deal-name">{% trans "Назва угоди" %}</th>
                                            <th class="hidden-xs">{% trans "Статус" %}</th>
                                            <th class="hidden-xs">{% trans "Сума" %}</th>
                                            <th class="hidden-xs">{% trans "Роль" %}</th>
                                            <th class="hidden-xs">{% trans "Дата" %}</th>
                                            <th>{% trans "Дії" %}</th>
                                        </tr>
                                        <tr id="filter" class="js-filter-form accordian-body">
                                            <th class="js-change">{{ filter.form.spay_id }}</th>
                                            <th class="js-change deal-name">{{ filter.form.name__icontains }}</th>
                                            <th class="hidden-xs js-change">{{ filter.form.product_status_filter }}</th>
                                            <th class="hidden-xs js-change">{{ filter.form.price }}</th>
                                            <th class="hidden-xs js-change">{{ filter.form.role }}</th>
                                            <th class="hidden-xs js-date">{{ filter.form.created_date__date__gt }}-{{ filter.form.created_date__date__lt }}</th>
                                            <th></th>
                                        </tr>
                                        </thead>
                                        <tbody>

                                        {% for product in filter.qs %}
                                            <tr>
                                                <td class="accordion-toggle" data-toggle="collapse"
                                                    data-target="#demo-{{ product.spay_id }}">
                                                    <p class="spay-arrow">{{ product.spay_id }}</p>

                                                    <div> {% thumbnail product.image "65x65" crop="center" as im %}
                                                        <img src="{{ im.url }}">
                                                    {% endthumbnail %}
                                                    </div>
                                                </td>
                                                <td class="deal-name">{{ product.name }}</td>
                                                <td class="hidden-xs">{{ product.get_status_display }}</td>
                                                <td class="hidden-xs">{{ product.price }}</td>
                                                <td class="hidden-xs">{% if request.user == product.user %}
                                                    {% trans "Продавець" %}{% else %}
                                                    {% trans "Покупець" %} {% endif %}</td>
                                                <td class="hidden-xs">{{ product.updated_date }}</td>
                                                <td class="action">
                                                    <p>
                                                        <a class="copy-button"
                                                           data-clipboard-text="



                                                                   {{ request.get_host }}{% url 'product:details_by_spay_id' product.spay_id %}">
                                                            <span class="glyphicon glyphicon-link"></span> {% trans "скопіювати лінк" %}
                                                        </a>
                                                    </p>

                                                    <p>
                                                        <a href="{% get_user_trade_url product request.user %}"><span
                                                                class="glyphicon glyphicon-list-alt"></span> {% trans "деталі" %}
                                                        </a>
                                                    </p>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td colspan="7" class="hiddenRow">
                                                    <div class="accordian-body collapse"
                                                         id="demo-{{ product.spay_id }}"><p
                                                            class="terms">
                                                        Умови продажу: {{ product.terms }}
                                                    </p></div>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="col-xs-12">
                    <h4 class="no-items">{% trans "Немає угод" %}</h4>
                </div>
            {% endif %}
        </div>
    </section>
{% endblock %}

{% block js %}
    <script type="application/javascript" src="{% static "js/bootstrap-datepicker.min.js" %}"></script>
    <script type="application/javascript" src="{% static "js/bootstrap-datepicker.ru.min.js" %}"></script>
    <script type="application/javascript" src="{% static "js/bootstrap-datepicker.uk.min.js" %}"></script>
    <script type="application/javascript" src="{% static "js/bootstrap-datepicker.pl.min.js" %}"></script>
    <script type="application/javascript">
        {% get_current_language as current_lang %}
        date_range = $('.js-date :input').datepicker({
            format: "mm/dd/yy",
            language: "{{ current_lang }}",
            autoclose: true,
            clearBtn: true,
            orientation: "bottom auto"
        });
        date_range.on('changeDate', function (ev) {
            $('#filter_form').submit();
        });
        $('.accordian-body.collapse').on('shown.bs.collapse hidden.bs.collapse', function () {
            $(this).closest('tr').prev().find(".spay-arrow").toggleClass("up")
        })
    </script>
{% endblock %}